### ISSUE TITLE
Implement environment manager

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/pydotfiles#42]
## Request
- Implement environment managers so that they are usable
- Plugins should be stubbed out, and completed in a followup issue (#43)

**Comment by JasonYao** [comment]
So, I should think about this a bit-

## Goals
- Be able to have an easily customizable, dev environment as config
- Be able to add in a new one by changing an array somewhere
- Be able to support macOS and linux

## Possible Approaches
- The current solution of having a `development_environment` listing
- Using the already-built `applications` to install `pyenv`/`rbenv` or whatever, and then throw the rest into a `post` script
  - Cons: would have to either duplicate the script for nix systems, when I really want this to work for multiple.

**Comment by JasonYao** [comment]
## Runtime log from current PR
```
(pydotfiles-3.6.7) []jason@Jasons-MacBook-Pro pydotfiles $ []pydotfiles install
[USER] Sudo: Actions requiring sudo actions have been detected, please enter your password below (your password is NOT stored at any point in time)
Password:
2019-02-11 04:54:19 AM [INFO::pydotfiles.models]: Install: Installing module [name=macos]
  [ .. ] Background Image: Checking background image status
  [ OK ] Background: Desktop image is now correctly set
2019-02-11 04:54:19 AM [INFO::pydotfiles.models]: Package: Already installed [Package=bash]
<snip>
2019-02-11 04:54:19 AM [INFO::pydotfiles.models]: Application: Already installed [Application=torguard]
2019-02-11 04:54:19 AM [INFO::pydotfiles.models]: Application: Already installed [Application=flux]
<snip>
2019-02-11 04:54:19 AM [INFO::pydotfiles.models]: Setting: Default setting already set [default_setting=Keyboard: Disabling accent character pop-up, description=Disable press-and-hold accent character pop-up in favor of key repeat]
<snip>
2019-02-11 04:54:21 AM [INFO::pydotfiles.models]: Action: Starting action [Action=COPY /Users/jason/.dotfiles/macos/fonts/FreeMono.ttf -> /Users/jason/Library/Fonts/FreeMono.ttf]
2019-02-11 04:54:21 AM [INFO::pydotfiles.models]: Action: Successfully completed action [Action=COPY /Users/jason/.dotfiles/macos/fonts/FreeMono.ttf -> /Users/jason/Library/Fonts/FreeMono.ttf]
<snip>
2019-02-11 04:54:21 AM [INFO::pydotfiles.models]: Install: Successfully installed module [name=ssh]
2019-02-11 04:54:21 AM [INFO::pydotfiles.models]: Install: Skipping operating system installation due to OS mismatch [HostOS=OS.MACOS, ModuleOS=OS.LINUX]
2019-02-11 04:54:21 AM [INFO::pydotfiles.models]: Install: Installing module [name=dev_environment]
2019-02-11 04:54:21 AM [INFO::pydotfiles.environments]: Development Environment: Installing [lang=python, versions=['3.7.2', '3.6.8', '2.7.15'], env_manager=<pydotfiles.environments.LanguageEnvironmentManager object at 0x1107d7f28>
2019-02-11 04:54:21 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language environment manager [env_manager=LanguageManager.PYENV]
2019-02-11 04:54:21 AM [INFO::pydotfiles.environments]: Language Environment Manager: Installing language version (this might take a bit, ~2 min) [language=python, version=3.7.2]
2019-02-11 04:56:42 AM [INFO::pydotfiles.environments]: Language Environment Manager: Successfully installed language version [language=python, version=3.7.2]
2019-02-11 04:56:42 AM [INFO::pydotfiles.environments]: Language Environment Manager: Installing language version (this might take a bit, ~2 min) [language=python, version=3.6.8]
2019-02-11 04:58:22 AM [INFO::pydotfiles.environments]: Language Environment Manager: Successfully installed language version [language=python, version=3.6.8]
2019-02-11 04:58:22 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language version [language=python, version=2.7.15]
2019-02-11 04:58:22 AM [INFO::pydotfiles.environments]: Development Environment: Successfully installed [lang=python, versions=['3.7.2', '3.6.8', '2.7.15'], env_manager=<pydotfiles.environments.LanguageEnvironmentManager object at 0x1107d7f28>
2019-02-11 04:58:22 AM [INFO::pydotfiles.environments]: Development Environment: Installing [lang=ruby, versions=['2.4.1'], env_manager=<pydotfiles.environments.LanguageEnvironmentManager object at 0x1107da358>
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/pydotfiles-3.6.7/bin/pydotfiles", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/bin/pydotfiles", line 13, in <module>
    main(sys.argv)
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/bin/pydotfiles", line 9, in main
    dispatcher.dispatch()
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/api/__init__.py", line 58, in dispatch
    getattr(self, args.command)(command_arguments)
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/api/__init__.py", line 111, in install
    self.dotfiles.install_all()
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/models/__init__.py", line 116, in install_all
    module.install()
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/models/__init__.py", line 223, in install
    environment.install()
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/environments/__init__.py", line 27, in install
    self.language_environment_manager.install()
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/environments/__init__.py", line 82, in install
    if self.is_installed:
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/environments/__init__.py", line 79, in is_installed
    raise NotImplementedError("Language Environment Manager: Sorry, the requested language manager is not currently supported (feel free to open an issue at https://github.com/JasonYao/pydotfiles/issues/new)")
NotImplementedError: Language Environment Manager: Sorry, the requested language manager is not currently supported (feel free to open an issue at https://github.com/JasonYao/pydotfiles/issues/new)
```

**Comment by JasonYao** [comment]
Got rid of the `rbenv` config, and running again:
```
2019-02-11 04:59:17 AM [INFO::pydotfiles.environments]: Development Environment: Installing [lang=python, versions=['3.7.2', '3.6.8', '2.7.15'], env_manager=<pydotfiles.environments.LanguageEnvironmentManager object at 0x10cc91f60>
2019-02-11 04:59:17 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language environment manager [env_manager=LanguageManager.PYENV]
2019-02-11 04:59:17 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language version [language=python, version=3.7.2]
2019-02-11 04:59:17 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language version [language=python, version=3.6.8]
2019-02-11 04:59:17 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language version [language=python, version=2.7.15]
2019-02-11 04:59:17 AM [INFO::pydotfiles.environments]: Development Environment: Successfully installed [lang=python, versions=['3.7.2', '3.6.8', '2.7.15'], env_manager=<pydotfiles.environments.LanguageEnvironmentManager object at 0x10cc91f60>
2019-02-11 04:59:17 AM [INFO::pydotfiles.environments]: Development Environment: Installing [lang=java, versions=['8', 'latest'], env_manager=<pydotfiles.environments.LanguageEnvironmentManager object at 0x10cc96208>
2019-02-11 04:59:17 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language environment manager [env_manager=LanguageManager.JENV]
2019-02-11 04:59:18 AM [INFO::pydotfiles.environments]: Language Environment Manager: Installing language version [language=java, version=8]
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/pydotfiles-3.6.7/bin/pydotfiles", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/bin/pydotfiles", line 13, in <module>
    main(sys.argv)
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/bin/pydotfiles", line 9, in main
    dispatcher.dispatch()
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/api/__init__.py", line 58, in dispatch
    getattr(self, args.command)(command_arguments)
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/api/__init__.py", line 111, in install
    self.dotfiles.install_all()
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/models/__init__.py", line 116, in install_all
    module.install()
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/models/__init__.py", line 223, in install
    environment.install()
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/environments/__init__.py", line 30, in install
    self.language_environment_manager.install_language_version(version)
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/environments/__init__.py", line 92, in install_language_version
    install_language(self.language_manager, version, self.sudo_password)
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/environments/__init__.py", line 143, in install_language
    install_java_version_via_homebrew(language_version, sudo_password)
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/environments/__init__.py", line 247, in install_java_version_via_homebrew
    run_command_with_communication(command, sudo_password)
  File "/Users/jason/Desktop/dotfiles/pydotfiles/pydotfiles/utils/io.py", line 205, in run_command_with_communication
    stdout, stderr = process.communicate(communication + '\n', timeout=3)
  File "/usr/local/var/pyenv/versions/3.6.7/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/var/pyenv/versions/3.6.7/lib/python3.6/subprocess.py", line 1515, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/local/var/pyenv/versions/3.6.7/lib/python3.6/subprocess.py", line 871, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['brew', 'cask', 'install', 'java8']' timed out after 3 seconds
```

**Comment by JasonYao** [comment]
```
2019-02-11 05:04:05 AM [INFO::pydotfiles.models]: Install: Installing module [name=dev_environment]
2019-02-11 05:04:05 AM [INFO::pydotfiles.environments]: Development Environment: Installing [lang=python, versions=['3.7.2', '3.6.8', '2.7.15'], env_manager=<pydotfiles.environments.LanguageEnvironmentManager object at 0x10c793b00>
2019-02-11 05:04:05 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language environment manager [env_manager=LanguageManager.PYENV]
2019-02-11 05:04:05 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language version [language=python, version=3.7.2]
2019-02-11 05:04:06 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language version [language=python, version=3.6.8]
2019-02-11 05:04:06 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language version [language=python, version=2.7.15]
2019-02-11 05:04:06 AM [INFO::pydotfiles.environments]: Development Environment: Successfully installed [lang=python, versions=['3.7.2', '3.6.8', '2.7.15'], env_manager=<pydotfiles.environments.LanguageEnvironmentManager object at 0x10c793b00>
2019-02-11 05:04:06 AM [INFO::pydotfiles.environments]: Development Environment: Installing [lang=java, versions=['8', 'latest'], env_manager=<pydotfiles.environments.LanguageEnvironmentManager object at 0x10c7970f0>
2019-02-11 05:04:06 AM [INFO::pydotfiles.environments]: Language Environment Manager: Already installed language environment manager [env_manager=LanguageManager.JENV]
2019-02-11 05:04:07 AM [INFO::pydotfiles.environments]: Language Environment Manager: Installing language version [language=java, version=8]
2019-02-11 05:04:33 AM [INFO::pydotfiles.environments]: Language Environment Manager: Successfully installed language version [language=java, version=8]
2019-02-11 05:04:34 AM [INFO::pydotfiles.environments]: Language Environment Manager: Installing language version [language=java, version=latest]
2019-02-11 05:04:37 AM [INFO::pydotfiles.environments]: Development Environment: Successfully installed [lang=java, versions=['8', 'latest'], env_manager=<pydotfiles.environments.LanguageEnvironmentManager object at 0x10c7970f0>
2019-02-11 05:04:37 AM [INFO::pydotfiles.models]: Install: Successfully installed module [name=dev_environment]
```

**Comment by JasonYao** [comment]
Hmm think that worked with the removal of the timeout. letting this soak for now and coming back to this later to verify
