### ISSUE TITLE
update readme to use initial https instead of ssh to clone

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/pydotfiles#77]
otherwise cloning fails during `setup-opinionated`

**Comment by JasonYao** [comment]
other issues:
```
jason@Jasons-MacBook-Pro .dotfiles % curl -s https://raw.githubusercontent.com/JasonYao/pydotfiles/master/start-opinionated | bash -s git@github.com:JasonYao/dotfiles.git
          [ OK ] Xcode: MacOS command-line tools are already installed
	  [INFO] Package Manager: Checking for the existance of Homebrew
          [ OK ] Package Manager: Homebrew is already installed
	  [INFO] Pyenv: Checking for pyenv installation
          [ OK ] Pyenv: Pyenv is already installed
	  [INFO] Pyenv Environment: Checking for correct pyenv environment variable setup
          [ OK ] Pyenv Environment: Already have set pyenv environment variables
	  [INFO] Pyenv Base Environment: Checking that all pyenv base environments are installed
          [ OK ] Pyenv: Python version 3.7.0 is already installed
          [ OK ] Pyenv: Python version 2.7.15 is already installed
          [ OK ] Pyenv Base Environment: All pyenv base environments look good
	  [INFO] Pyenv-virtualenv: Checking for pyenv-virtualenv installation
          [ OK ] Pyenv-virtualenv: Pyenv-virtualenv is already installed
	  [INFO] Pyenv Global Shim: Checking that all pyenv global environments are installed
          [ OK ] Pyenv Global Shim: The shim 'default-3.7.0' is already installed
          [ OK ] Pyenv Global Shim: The shim 'default-2.7.15' is already installed
          [ OK ] Pyenv Global Shim: All pyenv global environments look good
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
          [ OK ] Pyenv Primary Venv: Successfully set primary shim 'default-3.7.0' as the global default
You are using pip version 10.0.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
          [ OK ] Pydotfiles: Already installed pydotfiles
/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/pydotfiles/models/utils.py:79: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(config_fd)
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/default-3.7.0/bin/pydotfiles", line 13, in <module>
    main(sys.argv)
  File "/usr/local/var/pyenv/versions/default-3.7.0/bin/pydotfiles", line 9, in main
    dispatcher.dispatch()
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/pydotfiles/api/__init__.py", line 58, in dispatch
    getattr(self, args.command)(command_arguments)
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/pydotfiles/api/__init__.py", line 82, in download
    self.dotfiles = Dotfiles(config_repo_local, config_repo_remote, args.quiet, args.verbose)
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/pydotfiles/models/__init__.py", line 56, in __init__
    module_information = load_active_modules(config_repo_local, active_modules, self.host_os, self.cache_directory) if self.is_cloned else None
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/pydotfiles/models/__init__.py", line 857, in load_active_modules
    cache_directory=cache_directory
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/pydotfiles/models/__init__.py", line 197, in __init__
    settings_data = load_data_from_file(self.settings_file)
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/pydotfiles/models/utils.py", line 79, in load_data_from_file
    return yaml.load(config_fd)
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/parser.py", line 384, in parse_block_sequence_entry
    if not self.check_token(BlockEntryToken, BlockEndToken):
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/var/pyenv/versions/3.7.0/envs/default-3.7.0/lib/python3.7/site-packages/yaml/scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/Users/jason/.dotfiles/macos/settings.yaml", line 71, column 1
          [FAIL] Pydotfiles: Failed to download the pydotfiles configurations
jason@Jasons-MacBook-Pro .dotfiles % 

```
